pull_request_rules:
  - name: Approve PR
    conditions:
      - status-success=Run Tests
      - status-success=Lint Files
      - status-success=Deploy Draft
    actions:
      review:
        message: Checks Passed

  - name: Merge Dependabot
    conditions:
      - status-success=Run Tests
      - status-success=Lint Files
      - status-success=Deploy Draft
      - author=dependabot-preview[bot]
    actions:
      merge:
        method: squash
