pull_request_rules:
  - name: Approve PR
    conditions:
      - status-success=Run Tests
      - status-success=Lint Files
      - status-success=Deploy Draft
    actions:
      review:
        message: Checks Passed

  - name: Merge Dependabot
    conditions:
      - author=dependabot-preview[bot]
    actions:
      merge:
        method: squash

  - name: Merge Owner PR's
    conditions:
      - label=mergify
      - author=matanui159
    actions:
      merge:
        method: squash

  - name: Merge Owner Reviewed
    conditions:
      - label=mergify
      - approved-reviews-by=matanui159
    actions:
      merge:
        method: squash
