name: CI
on: push

jobs:
  install:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules

  wasm:
    name: Build WebAssembly
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library:
          - webp
          - jp2
          - heif
          - raw
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
      - uses: mymindstorm/setup-emsdk@v4
      - run: make -C wasm/${{ matrix.library }} ci -j4
      - uses: actions/cache@v1
        with:
          key: ${{ matrix.library }}-${{ github.sha }}
          path: wasm/${{ matrix.library }}

  build:
    name: Build Website
    runs-on: ubuntu-latest
    needs:
      - install
      - wasm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - uses: actions/cache@v1
        with:
          key: webp-${{ github.sha }}
          path: wasm/webp
      - uses: actions/cache@v1
        with:
          key: jp2-${{ github.sha }}
          path: wasm/jp2
      - uses: actions/cache@v1
        with:
          key: heif-${{ github.sha }}
          path: wasm/heif
      - uses: actions/cache@v1
        with:
          key: raw-${{ github.sha }}
          path: wasm/raw
      - run: yarn build
      - uses: actions/cache@v1
        with:
          key: build-${{ github.sha }}
          path: public

  lint:
    name: Lint Files
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - run: yarn lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - run: yarn test
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  deploy:
    name: Deploy Draft
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: build-${{ github.sha }}
          path: public
      - uses: netlify/actions/cli@master
        with:
          args: deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  deploy-prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      - test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: build-${{ github.sha }}
          path: public
      - uses: netlify/actions/cli@master
        with:
          args: deploy --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
