name: Build & Checks
on: push

jobs:
  install:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules

  webp:
    name: Build WebP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
      - uses: mymindstorm/setup-emsdk@v4
      - run: make -C wasm/webp -j4
      - uses: actions/cache@v1
        with:
          key: webp-${{ github.sha }}
          path: wasm/webp

  build:
    name: Build Website
    runs-on: ubuntu-latest
    needs:
      - install
      - webp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - uses: actions/cache@v1
        with:
          key: webp-${{ github.sha }}
          path: wasm/webp
      - run: yarn build
      - uses: actions/cache@v1
        with:
          key: build-${{ github.sha }}
          path: public

  lint:
    name: Lint Files
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - run: yarn lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - run: yarn test
      - uses: codecov/codecov-action@v1

  e2e-chrome:
    name: Run Chromium Tests
    runs-on: ubuntu-latest
    needs:
      - install
      - webp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get update
      - run: sudo apt-get install libnss3 libxss1 libasound2
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - uses: actions/cache@v1
        with:
          key: webp-${{ github.sha }}
          path: wasm/webp
      - run: yarn test-e2e --browsers Chromium

  e2e-firefox:
    name: Run Firefox Tests
    runs-on: ubuntu-latest
    needs:
      - install
      - webp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get update
      - run: sudo apt-get install libdbus-glib-1-2 libxt6
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - uses: actions/cache@v1
        with:
          key: webp-${{ github.sha }}
          path: wasm/webp
      - run: yarn test-e2e --browsers Firefox

  e2e-webkit:
    name: Run WebKit Tests
    runs-on: ubuntu-latest
    needs:
      - install
      - webp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get update
      - run: sudo apt-get install -y libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libnotify4 libxslt1.1 libevent-2.1-6 libgles2 libvpx5
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - uses: actions/cache@v1
        with:
          key: webp-${{ github.sha }}
          path: wasm/webp
      - run: yarn test-e2e --browsers WebKit

  # e2e-safari:
  #   name: Run Safari Tests
  #   runs-on: macos-latest
  #   needs:
  #     - webp
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: 13
  #         java-package: jre
  #     - run: sudo safaridriver --enable
  #     - uses: actions/cache@v1
  #       with:
  #         key: webp-${{ github.sha }}
  #         path: wasm/webp
  #     - run: yarn --frozen-lockfile
  #     - run: yarn webdriver-manager update
  #     - run: yarn webdriver-manager start --detach
  #     - run: yarn test-e2e --browsers SafariWebdriver
