name: Build & Checks
on: push

jobs:
  install:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules

  webp:
    name: Build WebP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
      - uses: mymindstorm/setup-emsdk@v4
      - run: make -C wasm/webp
      - uses: actions/cache@v1
        with:
          key: webp-${{ github.sha }}
          path: wasm/webp

  raw:
    name: Build LibRaw
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
      - uses: mymindstorm/setup-emsdk@v4
      - run: make -C wasm/raw
      - uses: actions/cache@v1
      - with:
          key: raw-${{ github.sha }}
          path: wasm/raw

  build:
    name: Build Website
    runs-on: ubuntu-latest
    needs:
      - install
      - webp
      - raw
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - uses: actions/cache@v1
        with:
          key: webp-${{ github.sha }}
          path: wasm/webp
      - uses: actions/cache@v1
        with:
          key: raw-${{ github.sha }}
          path: wasm/raw
      - run: yarn build
      - uses: actions/cache@v1
        with:
          key: build-${{ github.sha }}
          path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          key: install-${{ github.sha }}
          path: node_modules
      - uses: actions/cache@v1
        with:
          key: build-${{ github.sha }}
          path: dist
      - run: yarn deploy --token ${{ secrets.FIREBASE_TOKEN }}
